tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

cask_args appdir: "/Applications"

brew "annie"
brew "axel"
brew "bash"
brew "coreutils"
brew "curl", args: ["with-nghttp2"]
brew "findutils"
brew "gdbm"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "go"
brew "grc"
brew "grep"
brew "icu4c"
brew "imagemagick"
brew "lnav"
brew "make"
brew "node"
brew "openssh"
brew "openssl@1.1"
brew "protobuf"
brew "python@3.8"
brew "ruby"
brew "tmux"
brew "tree"
brew "vim", args: ["with-override-system-vi"]
brew "wget"
brew "zsh"
brew "zsh-completions"

cask "cleanmymac"
cask "docker"
cask "dropbox"
cask "evernote"
cask "firefox"
cask "font-fira-code"
cask "font-inconsolata"
cask "font-open-sans"
cask "font-roboto"
cask "font-source-code-pro"
cask "font-ubuntu"
cask "fork"
cask "google-chrome"
cask "handbrake"
cask "iterm2"
cask "keka"
cask "mplayerx"
cask "plex-media-server"
cask "qlmarkdown"
cask "quicklook-json"
cask "postman"
cask "recordit"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "xld"
